# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Generative_AI_App.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17Generative_AI_App.proto\x12\x11Generative_AI_App\"\xdf\x01\n\tServerMsg\x12\x18\n\x0bquestion_id\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x15\n\x08question\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nstream_end\x18\x03 \x01(\x08H\x02\x88\x01\x01\x12\x14\n\x07penalty\x18\x04 \x01(\x01H\x03\x88\x01\x01\x12\x12\n\x05score\x18\x05 \x01(\x03H\x04\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x06 \x01(\tH\x05\x88\x01\x01\x42\x0e\n\x0c_question_idB\x0b\n\t_questionB\r\n\x0b_stream_endB\n\n\x08_penaltyB\x08\n\x06_scoreB\x08\n\x06_error\"U\n\tAnswerMsg\x12\x18\n\x0bquestion_id\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x13\n\x06\x61nswer\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x0e\n\x0c_question_idB\t\n\x07_answerB\x02H\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Generative_AI_App_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _SERVERMSG._serialized_start=47
  _SERVERMSG._serialized_end=270
  _ANSWERMSG._serialized_start=272
  _ANSWERMSG._serialized_end=357
# @@protoc_insertion_point(module_scope)
